export enum LogicalOperator {
  EQUAL_TO = 'EQUAL_TO',

  NOT_EQUAL_TO = 'NOT_EQUAL_TO',

  OBJECT_ = 'OBJECT_',

  OBJECT_NOT_EQUAL_TO = 'OBJECT_NOT_EQUAL_TO',

  GREATER_THAN = 'GREATER_THAN',

  LESS_THAN = 'LESS_THAN',

  GREATER_THAN_OR_EQUAL_TO = 'GREATER_THAN_OR_EQUAL_TO',

  LESS_THAN_OR_EQUAL_TO = 'LESS_THAN_OR_EQUAL_TO',

  NONE = 'NONE',
}
