export enum RequestValueSource {
  USER_INPUT = 'USER_INPUT',

  PAYMENT_DETAIL = 'PAYMENT_DETAIL',

  TRANSACTION_ID = 'TRANSACTION_ID',

  TRANSACTION_DETAILS = 'TRANSACTION_DETAILS',

  TRANSACTION_AMOUNT = 'TRANSACTION_AMOUNT',

  CUSTOMER_PHONE = 'CUSTOMER_PHONE',

  CUSTOMER_EMAIL = 'CUSTOMER_EMAIL',

  CUSTOMER_ACCOUNT = 'CUSTOMER_ACCOUNT',

  NONE = 'NONE',
}
